name: Mr.yang 的博客

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm install -g hexo-cli
      - run: hexo generate
      - uses: manyuanrong/setup-ossutil@v1.0
  with:
    endpoint: "oss-cn-shanghai.aliyuncs.com"
    access-key-id: ${{ secrets.KEY  }}
    access-key-secret: ${{ secrets.SECRET }}
- run: ossutil cp -rf public oss://yanghongtao-blog/
